config/routes.rb
Rails.application.routes.draw do
	root 'pages#home'
	get 'auth/:provider/callback', to: 'sessions#create'
	get 'login', to: redirect('/auth/okta'), as: 'login'
	get 'logout' => 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
	  @user = auth
	  session[:user] = auth.uid
	  session[:email] = auth.extra.raw_info.email
	  session[:name] = auth.extra.raw_info.name
	  session[:firstname] = auth.extra.raw_info.given_name
	  session[:lastname] = auth.extra.raw_info.family_name
	  session[:groups] = auth.extra.raw_info.groups
	  redirect_to root_path	
  end

  def destroy
	  session[:user] = nil
	  session[:email] = nil
	  session[:name] = nil
	  session[:firstname] = nil
	  session[:lastname] = nil
	  session[:groups] = nil
	  redirect_to root_path
  end

  protected

  def auth
	  request.env["omniauth.auth"]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Crm</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

<% unless session[:user] %>
	<%= link_to 'Login', login_path %>
<% end %>
<% if session[:user] %>
	Logged in as
	<%= session[:name] %>
	<%= link_to 'Logout', logout_path %>
<% end %>
<hr/>
<%= session[:user] %><br/>
<%= session[:email] %><br/>
<%= session[:name] %><br/>
<%= session[:firstname] %><br/>
<%= session[:lastname] %><br/>
<%= session[:groups] %>